// ═══════════════════════════════════════════════════════════════════════════════
//                    KIRIKKALE OLİMPİYAT SPOR KULÜBÜ
//                         Bildirim Servisi v2.0
// ═══════════════════════════════════════════════════════════════════════════════

const Notification = require('../models/Notification');
const Payment = require('../models/Payment');
const Athlete = require('../models/Athlete');
const config = require('../config/config');
const logger = require('./logger');
const smsService = require('./smsService');

class NotificationService {
  // ─────────────────────────────────────────────────────────────────────────────
  // Yeni bildirim oluştur
  // ─────────────────────────────────────────────────────────────────────────────
  static async create(data) {
    try {
      const notification = await Notification.create({
        type: data.type,
        title: data.title,
        message: data.message,
        priority: data.priority || 'medium',
        relatedData: data.relatedData || {},
        targetAdmin: data.targetAdmin || null,
        isAutoGenerated: data.isAutoGenerated || false,
        actionUrl: data.actionUrl || null
      });
      
      logger.info('Notification created', { type: data.type, title: data.title });
      return notification;
    } catch (error) {
      logger.error('Bildirim oluşturma hatası', { error: error.message });
      throw error;
    }
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // Ödeme hatırlatması kontrolü
  // ─────────────────────────────────────────────────────────────────────────────
  static async checkPaymentReminders() {
    try {
      const reminderDays = config.NOTIFICATIONS.PAYMENT_REMINDER_DAYS;
      const targetDate = new Date();
      targetDate.setDate(targetDate.getDate() + reminderDays);

      // Yaklaşan vadeli ödemeler
      const upcomingPayments = await Payment.find({
        status: { $in: ['Beklemede', 'Gecikmiş'] },
        reminderSent: false,
        dueDate: { $lte: targetDate }
      }).populate('athlete', 'firstName lastName phone guardian');

      let notificationsCreated = 0;
      let smsSent = 0;

      for (const payment of upcomingPayments) {
        if (!payment.athlete) continue;
        
        const isOverdue = new Date() > new Date(payment.dueDate);
        const periodName = payment.paymentType === 'Aylık' 
          ? payment.periodName 
          : `${payment.packageNumber}. Paket`;
        
        // Panel bildirimi oluştur
        await this.create({
          type: 'payment_reminder',
          title: isOverdue ? '⚠️ Gecikmiş Ödeme!' : '💳 Yaklaşan Ödeme Hatırlatması',
          message: `${payment.athlete.firstName} ${payment.athlete.lastName} - ${periodName} için ${payment.amount}₺ ${isOverdue ? 'ödeme gecikmiş' : 'ödeme vadesi yaklaşıyor'}.`,
          priority: isOverdue ? 'urgent' : 'high',
          relatedData: {
            athleteId: payment.athlete._id,
            paymentId: payment._id
          },
          isAutoGenerated: true,
          actionUrl: `/odemeler`
        });
        notificationsCreated++;

        // SMS gönder
        const phone = payment.athlete.phone || payment.athlete.guardian?.phone;
        if (phone && config.NETGSM.enabled) {
          const dueDate = new Date(payment.dueDate).toLocaleDateString('tr-TR');
          await smsService.sendPaymentReminder(
            phone,
            `${payment.athlete.firstName} ${payment.athlete.lastName}`,
            payment.amount,
            dueDate
          );
          smsSent++;
        }

        // Hatırlatma gönderildi olarak işaretle
        payment.reminderSent = true;
        await payment.save();
      }

      logger.info('Payment reminders processed', { 
        notifications: notificationsCreated, 
        sms: smsSent 
      });
      
      return { notifications: notificationsCreated, sms: smsSent };
    } catch (error) {
      logger.error('Ödeme hatırlatma kontrolü hatası', { error: error.message });
      throw error;
    }
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // Düşük seans hakkı hatırlatması kontrolü
  // ─────────────────────────────────────────────────────────────────────────────
  static async checkSessionReminders() {
    try {
      // 2 veya daha az seans hakkı kalan sporcular
      const lowSessionAthletes = await Athlete.find({
        status: 'Aktif',
        membershipType: '8 Seanslık',
        remainingSessions: { $lte: 2, $gt: 0 }
      });

      let notificationsCreated = 0;
      let smsSent = 0;

      for (const athlete of lowSessionAthletes) {
        // Aynı sporcu için son 24 saatte bildirim var mı kontrol et
        const existingNotification = await Notification.findOne({
          type: 'session_ending',
          'relatedData.athleteId': athlete._id,
          createdAt: { $gte: new Date(Date.now() - 24 * 60 * 60 * 1000) }
        });

        if (!existingNotification) {
          // Panel bildirimi
          await this.create({
            type: 'session_ending',
            title: '⚠️ Seans Hakkı Azalıyor',
            message: `${athlete.firstName} ${athlete.lastName} - Sadece ${athlete.remainingSessions} seans hakkı kaldı. Paket yenileme gerekebilir.`,
            priority: athlete.remainingSessions <= 1 ? 'high' : 'medium',
            relatedData: {
              athleteId: athlete._id
            },
            isAutoGenerated: true,
            actionUrl: `/sporcular/${athlete._id}`
          });
          notificationsCreated++;

          // SMS gönder
          const phone = athlete.phone || athlete.guardian?.phone;
          if (phone && config.NETGSM.enabled) {
            await smsService.sendSessionWarning(
              phone,
              `${athlete.firstName} ${athlete.lastName}`,
              athlete.remainingSessions
            );
            smsSent++;
          }
        }
      }

      logger.info('Session reminders processed', { 
        notifications: notificationsCreated, 
        sms: smsSent 
      });
      
      return { notifications: notificationsCreated, sms: smsSent };
    } catch (error) {
      logger.error('Seans hatırlatma kontrolü hatası', { error: error.message });
      throw error;
    }
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // Yeni kayıt bildirimi
  // ─────────────────────────────────────────────────────────────────────────────
  static async createNewRegistrationNotification(registration) {
    // Panel bildirimi
    const notification = await this.create({
      type: 'new_registration',
      title: '🆕 Yeni Online Kayıt',
      message: `${registration.firstName} ${registration.lastName} online kayıt formunu doldurdu. Kayıt onayı bekliyor.`,
      priority: 'medium',
      relatedData: {},
      isAutoGenerated: true,
      actionUrl: '/kayitlar'
    });

    // SMS ile veli'ye onay gönder
    const phone = registration.phone || registration.guardian?.phone;
    if (phone && config.NETGSM.enabled) {
      await smsService.sendRegistrationConfirmation(
        phone,
        `${registration.firstName} ${registration.lastName}`
      );
    }

    return notification;
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // Ödeme alındı bildirimi
  // ─────────────────────────────────────────────────────────────────────────────
  static async createPaymentReceivedNotification(payment, athlete) {
    // Panel bildirimi
    const notification = await this.create({
      type: 'payment_received',
      title: '✅ Ödeme Alındı',
      message: `${athlete.firstName} ${athlete.lastName} - ${payment.periodName || payment.paymentType} dönemi için ${payment.amount}₺ ödeme alındı.`,
      priority: 'low',
      relatedData: {
        athleteId: athlete._id,
        paymentId: payment._id
      },
      isAutoGenerated: true,
      actionUrl: `/sporcular/${athlete._id}`
    });

    // SMS ile veli'ye onay gönder
    const phone = athlete.phone || athlete.guardian?.phone;
    if (phone && config.NETGSM.enabled) {
      await smsService.sendPaymentConfirmation(
        phone,
        `${athlete.firstName} ${athlete.lastName}`,
        payment.amount
      );
    }

    return notification;
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // Manuel bildirim gönder
  // ─────────────────────────────────────────────────────────────────────────────
  static async sendCustomNotification(data) {
    const notification = await this.create({
      type: 'custom',
      title: data.title,
      message: data.message,
      priority: data.priority || 'medium',
      relatedData: data.relatedData || {},
      targetAdmin: data.targetAdmin,
      isAutoGenerated: false,
      actionUrl: data.actionUrl
    });

    // SMS gönder (eğer telefon ve mesaj varsa)
    if (data.phone && data.sendSms && config.NETGSM.enabled) {
      await smsService.sendCustomMessage(data.phone, data.message);
    }

    return notification;
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // Toplu SMS gönder
  // ─────────────────────────────────────────────────────────────────────────────
  static async sendBulkSMS(phones, message) {
    if (!config.NETGSM.enabled) {
      return {
        success: false,
        message: 'SMS servisi devre dışı'
      };
    }

    return await smsService.sendBulk(phones, message);
  }
}

module.exports = NotificationService;
