// ═══════════════════════════════════════════════════════════════════════════════
//                    KIRIKKALE OLİMPİYAT SPOR KULÜBÜ
//                         Bildirim Servisi v3.0
//                    BozkurtSMS Entegrasyonu ile Güncellenmiş
// ═══════════════════════════════════════════════════════════════════════════════

const Notification = require('../models/Notification');
const Payment = require('../models/Payment');
const Athlete = require('../models/Athlete');
const SMSLog = require('../models/SMSLog');
const config = require('../config/config');
const logger = require('./logger');
const smsService = require('./smsService');

class NotificationService {
  // ─────────────────────────────────────────────────────────────────────────────
  // Yeni bildirim oluştur
  // ─────────────────────────────────────────────────────────────────────────────
  static async create(data) {
    try {
      const notification = await Notification.create({
        type: data.type,
        title: data.title,
        message: data.message,
        priority: data.priority || 'medium',
        relatedData: data.relatedData || {},
        targetAdmin: data.targetAdmin || null,
        isAutoGenerated: data.isAutoGenerated || false,
        actionUrl: data.actionUrl || null
      });
      
      logger.info('Notification created', { type: data.type, title: data.title });
      return notification;
    } catch (error) {
      logger.error('Bildirim oluşturma hatası', { error: error.message });
      throw error;
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════════
  // AYLIK ÖDEME HATIRLATALARI
  // ═══════════════════════════════════════════════════════════════════════════════

  /**
   * Aylık ödeme hatırlatması kontrolü
   * - Vade tarihine 1 gün kala SMS gönderir
   * - Vadesi geçmiş ödemelere süre doldu SMS'i gönderir
   */
  static async checkPaymentReminders() {
    try {
      const reminderDays = config.NOTIFICATIONS.PAYMENT_REMINDER_DAYS; // 1 gün
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      
      // Yarınki tarih (1 gün sonra)
      const targetDate = new Date(today);
      targetDate.setDate(targetDate.getDate() + reminderDays);
      targetDate.setHours(23, 59, 59, 999);

      let notificationsCreated = 0;
      let smsSent = 0;

      // ═══════════════════════════════════════════════════════════════════════
      // 1. YAKLAŞAN ÖDEMELER (1 gün kala)
      // ═══════════════════════════════════════════════════════════════════════
      const upcomingPayments = await Payment.find({
        status: { $in: ['Beklemede', 'Kısmi Ödeme'] },
        paymentType: 'Aylık',
        reminderSent: false,
        dueDate: {
          $gte: today,
          $lte: targetDate
        }
      }).populate('athlete', 'firstName lastName phone guardian tcNo');

      for (const payment of upcomingPayments) {
        if (!payment.athlete) continue;
        
        const periodName = payment.periodName;
        
        // Panel bildirimi oluştur
        await this.create({
          type: 'payment_reminder',
          title: '💳 Yaklaşan Ödeme Hatırlatması',
          message: `${payment.athlete.firstName} ${payment.athlete.lastName} - ${periodName} için ${payment.amount}₺ ödeme vadesi yaklaşıyor (1 gün kaldı).`,
          priority: 'high',
          relatedData: {
            athleteId: payment.athlete._id,
            paymentId: payment._id
          },
          isAutoGenerated: true,
          actionUrl: `/odemeler`
        });
        notificationsCreated++;

        // SMS gönder
        const phone = payment.athlete.phone || payment.athlete.guardian?.phone;
        if (phone && config.SMS.enabled && config.NOTIFICATIONS.AUTO_SMS_ENABLED) {
          const dueDate = new Date(payment.dueDate).toLocaleDateString('tr-TR');
          const result = await smsService.sendMonthlyPaymentReminder(
            phone,
            `${payment.athlete.firstName} ${payment.athlete.lastName}`,
            payment.amount,
            dueDate
          );
          
          if (result.success) smsSent++;
          
          // SMS log güncelle
          await SMSLog.findOneAndUpdate(
            { phone: smsService.formatPhone(phone), createdAt: { $gte: new Date(Date.now() - 5000) } },
            { athlete: payment.athlete._id, isAutomatic: true },
            { sort: { createdAt: -1 } }
          );
        }

        // Hatırlatma gönderildi olarak işaretle
        payment.reminderSent = true;
        await payment.save();
      }

      // ═══════════════════════════════════════════════════════════════════════
      // 2. VADESİ GEÇMİŞ ÖDEMELER (süre doldu mesajı)
      // ═══════════════════════════════════════════════════════════════════════
      const overduePayments = await Payment.find({
        status: { $in: ['Beklemede', 'Gecikmiş', 'Kısmi Ödeme'] },
        paymentType: 'Aylık',
        dueDate: { $lt: today }
      }).populate('athlete', 'firstName lastName phone guardian tcNo');

      for (const payment of overduePayments) {
        if (!payment.athlete) continue;
        
        // Günlük kontrol - aynı gün içinde tekrar SMS atma
        const todaySMSExists = await SMSLog.findOne({
          athlete: payment.athlete._id,
          type: 'monthly_expired',
          createdAt: { $gte: today }
        });

        if (todaySMSExists) continue;

        // Gecikme durumunu güncelle
        if (payment.status !== 'Gecikmiş') {
          payment.status = 'Gecikmiş';
          await payment.save();
        }

        // Panel bildirimi (günde 1 kez)
        const existingNotification = await Notification.findOne({
          type: 'payment_reminder',
          'relatedData.paymentId': payment._id,
          createdAt: { $gte: today }
        });

        if (!existingNotification) {
          await this.create({
            type: 'payment_reminder',
            title: '⚠️ Gecikmiş Ödeme!',
            message: `${payment.athlete.firstName} ${payment.athlete.lastName} - ${payment.periodName} için ${payment.amount}₺ ödeme gecikmiş!`,
            priority: 'urgent',
            relatedData: {
              athleteId: payment.athlete._id,
              paymentId: payment._id
            },
            isAutoGenerated: true,
            actionUrl: `/odemeler`
          });
          notificationsCreated++;
        }

        // SMS gönder (vadesi geçtikten sonra 1 kez)
        const phone = payment.athlete.phone || payment.athlete.guardian?.phone;
        const expiredSMSSent = await SMSLog.findOne({
          athlete: payment.athlete._id,
          type: 'monthly_expired',
          'relatedData.paymentId': payment._id
        });

        if (phone && config.SMS.enabled && config.NOTIFICATIONS.AUTO_SMS_ENABLED && !expiredSMSSent) {
          const result = await smsService.sendMonthlyPaymentExpired(
            phone,
            `${payment.athlete.firstName} ${payment.athlete.lastName}`,
            payment.amount
          );
          
          if (result.success) smsSent++;
        }
      }

      logger.info('Payment reminders processed', { 
        notifications: notificationsCreated, 
        sms: smsSent 
      });
      
      return { notifications: notificationsCreated, sms: smsSent };
    } catch (error) {
      logger.error('Ödeme hatırlatma kontrolü hatası', { error: error.message });
      throw error;
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════════
  // SEANS HAKKI HATIRLATALARI
  // ═══════════════════════════════════════════════════════════════════════════════

  /**
   * Düşük seans hakkı hatırlatması kontrolü
   * - 1 seans kala uyarı SMS'i gönderir
   * - 0 seans kaldığında doldu SMS'i gönderir
   */
  static async checkSessionReminders() {
    try {
      const warningThreshold = config.NOTIFICATIONS.SESSION_WARNING_THRESHOLD; // 1 seans
      const today = new Date();
      today.setHours(0, 0, 0, 0);

      let notificationsCreated = 0;
      let smsSent = 0;

      // ═══════════════════════════════════════════════════════════════════════
      // 1. SEANS HAKKI AZALIYOR (1 seans kala)
      // ═══════════════════════════════════════════════════════════════════════
      const lowSessionAthletes = await Athlete.find({
        status: 'Aktif',
        membershipType: '8 Seanslık',
        remainingSessions: warningThreshold
      });

      for (const athlete of lowSessionAthletes) {
        // Son 24 saatte bildirim var mı kontrol et
        const existingNotification = await Notification.findOne({
          type: 'session_ending',
          'relatedData.athleteId': athlete._id,
          createdAt: { $gte: new Date(Date.now() - 24 * 60 * 60 * 1000) }
        });

        if (!existingNotification) {
          // Panel bildirimi
          await this.create({
            type: 'session_ending',
            title: '⚠️ Seans Hakkı Azalıyor',
            message: `${athlete.firstName} ${athlete.lastName} - Sadece ${athlete.remainingSessions} seans hakkı kaldı. Paket yenileme gerekebilir.`,
            priority: 'high',
            relatedData: {
              athleteId: athlete._id
            },
            isAutoGenerated: true,
            actionUrl: `/sporcular/${athlete._id}`
          });
          notificationsCreated++;

          // SMS gönder
          const phone = athlete.phone || athlete.guardian?.phone;
          if (phone && config.SMS.enabled && config.NOTIFICATIONS.AUTO_SMS_ENABLED) {
            const result = await smsService.sendSessionWarning(
              phone,
              `${athlete.firstName} ${athlete.lastName}`,
              athlete.remainingSessions
            );
            
            if (result.success) smsSent++;
            
            // SMS log güncelle
            await SMSLog.findOneAndUpdate(
              { phone: smsService.formatPhone(phone), createdAt: { $gte: new Date(Date.now() - 5000) } },
              { athlete: athlete._id, isAutomatic: true },
              { sort: { createdAt: -1 } }
            );
          }
        }
      }

      // ═══════════════════════════════════════════════════════════════════════
      // 2. SEANS HAKKI DOLDU (0 seans)
      // ═══════════════════════════════════════════════════════════════════════
      const expiredSessionAthletes = await Athlete.find({
        status: 'Aktif',
        membershipType: '8 Seanslık',
        remainingSessions: 0
      });

      for (const athlete of expiredSessionAthletes) {
        // Bugün zaten SMS gönderilmiş mi?
        const todaySMSExists = await SMSLog.findOne({
          athlete: athlete._id,
          type: 'session_expired',
          createdAt: { $gte: today }
        });

        if (todaySMSExists) continue;

        // Panel bildirimi
        const existingNotification = await Notification.findOne({
          type: 'session_ending',
          'relatedData.athleteId': athlete._id,
          message: { $regex: /doldu/i },
          createdAt: { $gte: today }
        });

        if (!existingNotification) {
          await this.create({
            type: 'session_ending',
            title: '🚨 Seans Hakkı Doldu!',
            message: `${athlete.firstName} ${athlete.lastName} (TC: ${athlete.tcNo}) - Seans hakkı dolmuştur. Yeni paket gerekli.`,
            priority: 'urgent',
            relatedData: {
              athleteId: athlete._id
            },
            isAutoGenerated: true,
            actionUrl: `/sporcular/${athlete._id}`
          });
          notificationsCreated++;
        }

        // SMS gönder
        const phone = athlete.phone || athlete.guardian?.phone;
        if (phone && config.SMS.enabled && config.NOTIFICATIONS.AUTO_SMS_ENABLED) {
          const result = await smsService.sendSessionExpired(
            phone,
            `${athlete.firstName} ${athlete.lastName}`,
            athlete.tcNo
          );
          
          if (result.success) smsSent++;
        }
      }

      logger.info('Session reminders processed', { 
        notifications: notificationsCreated, 
        sms: smsSent 
      });
      
      return { notifications: notificationsCreated, sms: smsSent };
    } catch (error) {
      logger.error('Seans hatırlatma kontrolü hatası', { error: error.message });
      throw error;
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════════
  // DİĞER BİLDİRİMLER
  // ═══════════════════════════════════════════════════════════════════════════════

  /**
   * Yeni kayıt bildirimi
   */
  static async createNewRegistrationNotification(registration) {
    // Panel bildirimi
    const notification = await this.create({
      type: 'new_registration',
      title: '🆕 Yeni Online Kayıt',
      message: `${registration.firstName} ${registration.lastName} online kayıt formunu doldurdu. Kayıt onayı bekliyor.`,
      priority: 'medium',
      relatedData: {},
      isAutoGenerated: true,
      actionUrl: '/kayitlar'
    });

    // SMS ile veli'ye onay gönder
    const phone = registration.phone || registration.guardian?.phone;
    if (phone && config.SMS.enabled) {
      await smsService.sendRegistrationConfirmation(
        phone,
        `${registration.firstName} ${registration.lastName}`
      );
    }

    return notification;
  }

  /**
   * Ödeme alındı bildirimi
   */
  static async createPaymentReceivedNotification(payment, athlete) {
    // Panel bildirimi
    const notification = await this.create({
      type: 'payment_received',
      title: '✅ Ödeme Alındı',
      message: `${athlete.firstName} ${athlete.lastName} - ${payment.periodName || payment.paymentType} dönemi için ${payment.amount}₺ ödeme alındı.`,
      priority: 'low',
      relatedData: {
        athleteId: athlete._id,
        paymentId: payment._id
      },
      isAutoGenerated: true,
      actionUrl: `/sporcular/${athlete._id}`
    });

    // SMS ile veli'ye onay gönder
    const phone = athlete.phone || athlete.guardian?.phone;
    if (phone && config.SMS.enabled) {
      await smsService.sendPaymentConfirmation(
        phone,
        `${athlete.firstName} ${athlete.lastName}`,
        payment.amount
      );
    }

    return notification;
  }

  /**
   * Manuel bildirim gönder
   */
  static async sendCustomNotification(data) {
    const notification = await this.create({
      type: 'custom',
      title: data.title,
      message: data.message,
      priority: data.priority || 'medium',
      relatedData: data.relatedData || {},
      targetAdmin: data.targetAdmin,
      isAutoGenerated: false,
      actionUrl: data.actionUrl
    });

    // SMS gönder (eğer telefon ve mesaj varsa)
    if (data.phone && data.sendSms && config.SMS.enabled) {
      await smsService.sendCustomMessage(data.phone, data.message);
    }

    return notification;
  }

  /**
   * Toplu SMS gönder
   */
  static async sendBulkSMS(recipients, message, useTemplate = false) {
    if (!config.SMS.enabled) {
      return {
        success: false,
        message: 'SMS servisi devre dışı'
      };
    }

    return await smsService.sendBulk(recipients, message, useTemplate);
  }

  /**
   * Gruba SMS gönder
   */
  static async sendGroupSMS(groupType, message, useTemplate = false) {
    if (!config.SMS.enabled) {
      return {
        success: false,
        message: 'SMS servisi devre dışı'
      };
    }

    return await smsService.sendToGroup(groupType, message, useTemplate);
  }

  /**
   * SMS istatistiklerini al
   */
  static async getSMSStats(startDate, endDate) {
    return await smsService.getStats(startDate, endDate);
  }
}

module.exports = NotificationService;
