// ═══════════════════════════════════════════════════════════════════════════════
//                    KIRIKKALE OLİMPİYAT SPOR KULÜBÜ
//                         Bildirim Model - MongoDB Schema
// ═══════════════════════════════════════════════════════════════════════════════

const mongoose = require('mongoose');

const notificationSchema = new mongoose.Schema({
  // Bildirim Tipi
  type: {
    type: String,
    enum: ['payment_reminder', 'session_ending', 'new_registration', 'payment_received', 'system', 'custom'],
    required: true
  },
  
  // Başlık ve İçerik
  title: {
    type: String,
    required: [true, 'Bildirim başlığı zorunludur'],
    trim: true
  },
  message: {
    type: String,
    required: [true, 'Bildirim mesajı zorunludur'],
    trim: true
  },
  
  // Öncelik
  priority: {
    type: String,
    enum: ['low', 'medium', 'high', 'urgent'],
    default: 'medium'
  },
  
  // İlişkili Veriler
  relatedData: {
    athleteId: { type: mongoose.Schema.Types.ObjectId, ref: 'Athlete' },
    sessionId: { type: mongoose.Schema.Types.ObjectId, ref: 'Session' },
    paymentId: { type: mongoose.Schema.Types.ObjectId, ref: 'Payment' }
  },
  
  // Okundu Durumu
  isRead: {
    type: Boolean,
    default: false
  },
  readAt: {
    type: Date,
    default: null
  },
  
  // Hedef
  targetAdmin: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Admin',
    default: null // null = tüm adminler
  },
  
  // Otomatik oluşturuldu mu?
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  
  // Eylem Linki
  actionUrl: {
    type: String,
    default: null
  }
}, {
  timestamps: true
});

// Okunmamış bildirim sayısı
notificationSchema.statics.getUnreadCount = async function(adminId = null) {
  const query = { isRead: false };
  if (adminId) {
    query.$or = [{ targetAdmin: adminId }, { targetAdmin: null }];
  }
  return await this.countDocuments(query);
};

// Son bildirimleri al
notificationSchema.statics.getRecent = async function(limit = 10, adminId = null) {
  const query = {};
  if (adminId) {
    query.$or = [{ targetAdmin: adminId }, { targetAdmin: null }];
  }
  return await this.find(query)
    .sort({ createdAt: -1 })
    .limit(limit)
    .populate('relatedData.athleteId', 'firstName lastName')
    .populate('relatedData.sessionId', 'name');
};

// Indexler
notificationSchema.index({ isRead: 1 });
notificationSchema.index({ type: 1 });
notificationSchema.index({ createdAt: -1 });
notificationSchema.index({ targetAdmin: 1 });

module.exports = mongoose.model('Notification', notificationSchema);

